apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: election-reader
rules:
- apiGroups:
    - ""
    - apps
  resources: 
    - endpoints
    - replicasets
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: election-secrets-global
subjects:
- kind: ServiceAccount
  name: election-service-account
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: election-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: election-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: election-service
spec:
  selector:
    app: election
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: elector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: election
  template:
    metadata: 
      labels:
        app: election
    spec:
      serviceAccountName: election-service-account
      containers:
      - image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: elector
        args:
          - --election=example
          - --http=localhost:4040
        resources:
          requests:
            cpu: 100m